# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binomialTree <- function(S, K, T, r, u, d, p, steps) {
    .Call('_StructuredEdge_binomialTree', PACKAGE = 'StructuredEdge', S, K, T, r, u, d, p, steps)
}

blackScholes <- function(S, K, T, r, sigma, b) {
    .Call('_StructuredEdge_blackScholes', PACKAGE = 'StructuredEdge', S, K, T, r, sigma, b)
}

exchangeForward <- function(S, T, r_d, r_f) {
    .Call('_StructuredEdge_exchangeForward', PACKAGE = 'StructuredEdge', S, T, r_d, r_f)
}

finForwardContract <- function(S, T, r) {
    .Call('_StructuredEdge_finForwardContract', PACKAGE = 'StructuredEdge', S, T, r)
}

irForward <- function(r1, t1, t2, t_min, t_max, t_step) {
    .Call('_StructuredEdge_irForward', PACKAGE = 'StructuredEdge', r1, t1, t2, t_min, t_max, t_step)
}

physForwardContract <- function(S, T, r, c) {
    .Call('_StructuredEdge_physForwardContract', PACKAGE = 'StructuredEdge', S, T, r, c)
}

