# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binomialTree <- function(S, K, T, r, u, d, p, steps, option_type, position_str, nominal) {
    .Call(`_StructuredEdge_binomialTree`, S, K, T, r, u, d, p, steps, option_type, position_str, nominal)
}

blackScholes <- function(S, K, T, r, sigma, b, option_type, position_str, nominal) {
    .Call(`_StructuredEdge_blackScholes`, S, K, T, r, sigma, b, option_type, position_str, nominal)
}

exchangeForward <- function(S, T, r_d, r_f) {
    .Call(`_StructuredEdge_exchangeForward`, S, T, r_d, r_f)
}

finForwardContract <- function(S, T, r, position_str, nominal) {
    .Call(`_StructuredEdge_finForwardContract`, S, T, r, position_str, nominal)
}

irForward <- function(r1, r2, t1, t2, notional, position_str) {
    .Call(`_StructuredEdge_irForward`, r1, r2, t1, t2, notional, position_str)
}

physForwardContract <- function(S, T, r, c, position_str, nominal) {
    .Call(`_StructuredEdge_physForwardContract`, S, T, r, c, position_str, nominal)
}

physicalSwap <- function(quantity, fixed_price, spot_price) {
    .Call(`_StructuredEdge_physicalSwap`, quantity, fixed_price, spot_price)
}

