# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binomialTree <- function(S, K, T, r, u, d, p, steps, option_type, position_str, nominal, option_cost) {
    .Call(`_StructuredEdge_binomialTree`, S, K, T, r, u, d, p, steps, option_type, position_str, nominal, option_cost)
}

blackScholes <- function(S, K, T, r, sigma, b, option_type, position_str, nominal, option_cost) {
    .Call(`_StructuredEdge_blackScholes`, S, K, T, r, sigma, b, option_type, position_str, nominal, option_cost)
}

creditDefaultSwap <- function(credit_spread, default_probability_start, recovery_rate, period_length, discount_rate, position_str, nominal) {
    .Call(`_StructuredEdge_creditDefaultSwap`, credit_spread, default_probability_start, recovery_rate, period_length, discount_rate, position_str, nominal)
}

exchangeForward <- function(S, T, rd, rf, position_str, nominal) {
    .Call(`_StructuredEdge_exchangeForward`, S, T, rd, rf, position_str, nominal)
}

exchangeRateSwap <- function(fixed_rate, period_length, exchange_rate, discount_rate, position_str, nominal) {
    .Call(`_StructuredEdge_exchangeRateSwap`, fixed_rate, period_length, exchange_rate, discount_rate, position_str, nominal)
}

finForwardContract <- function(S, T, r, position_str, nominal) {
    .Call(`_StructuredEdge_finForwardContract`, S, T, r, position_str, nominal)
}

interestRateSwap <- function(fixed_rate, T, floating_rate, discount_rate, position_str, nominal) {
    .Call(`_StructuredEdge_interestRateSwap`, fixed_rate, T, floating_rate, discount_rate, position_str, nominal)
}

irForward <- function(r1, r2, t1, t2, nominal, position_str) {
    .Call(`_StructuredEdge_irForward`, r1, r2, t1, t2, nominal, position_str)
}

physForwardContract <- function(S, T, r, c, position_str, nominal) {
    .Call(`_StructuredEdge_physForwardContract`, S, T, r, c, position_str, nominal)
}

physicalSwap <- function(fixed_price, period_length, spot_price, discount_rate, position_str, nominal) {
    .Call(`_StructuredEdge_physicalSwap`, fixed_price, period_length, spot_price, discount_rate, position_str, nominal)
}

simulate_gbm_single <- function(num_steps, S0, mu, sigma, T) {
    .Call(`_StructuredEdge_simulate_gbm_single`, num_steps, S0, mu, sigma, T)
}

simulate_ou_single <- function(num_steps, X0, mu, theta, sigma, T) {
    .Call(`_StructuredEdge_simulate_ou_single`, num_steps, X0, mu, theta, sigma, T)
}

simulate_ouj_single <- function(num_steps, S0, mu, theta, sigma, Jump_prob, Jump_mean, sigma_JumpStdv, T) {
    .Call(`_StructuredEdge_simulate_ouj_single`, num_steps, S0, mu, theta, sigma, Jump_prob, Jump_mean, sigma_JumpStdv, T)
}

varianceSwap <- function(variance_strike, realized_variance_start, position_str, nominal) {
    .Call(`_StructuredEdge_varianceSwap`, variance_strike, realized_variance_start, position_str, nominal)
}

